// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         products: [{
 *                 id: "id"
 *             }],
 *         successUrl: "successUrl"
 *     }
 */
export interface CreateCheckoutRequest {
    products: Paid.CheckoutProductInput[];
    customerId?: string;
    /** External customer identifier. Creates the customer on first use, resolves to the existing customer on subsequent uses. */
    externalCustomerId?: string;
    successUrl: string;
    cancelUrl?: string;
    expiresAt?: string;
    metadata?: Record<string, unknown>;
    collectAddress?: boolean;
    collectPhone?: boolean;
    singleUse?: boolean;
}
