/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Paid from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";
import { Lines } from "../resources/lines/client/Client.js";

export declare namespace Orders {
    export interface Options {
        environment?: core.Supplier<environments.PaidEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Orders {
    protected readonly _options: Orders.Options;
    protected _lines: Lines | undefined;

    constructor(_options: Orders.Options = {}) {
        this._options = _options;
    }

    public get lines(): Lines {
        return (this._lines ??= new Lines(this._options));
    }

    /**
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.orders.list()
     */
    public list(requestOptions?: Orders.RequestOptions): core.HttpResponsePromise<Paid.Order[]> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(requestOptions?: Orders.RequestOptions): Promise<core.WithRawResponse<Paid.Order[]>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                "orders",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Order[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PaidError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling GET /orders.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Paid.OrderCreate} request
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.orders.create({
     *         customerExternalId: "acme-inc",
     *         name: "Acme Order",
     *         description: "Acme Order is an order for Acme, Inc.",
     *         startDate: "2025-01-01",
     *         endDate: "2026-01-01",
     *         currency: "USD"
     *     })
     *
     * @example
     *     await client.orders.create({
     *         customerExternalId: "acme-inc",
     *         name: "Acme Order with Custom Pricing",
     *         description: "Order with customized attribute pricing",
     *         startDate: "2025-01-01",
     *         endDate: "2026-01-01",
     *         currency: "USD"
     *     })
     */
    public create(
        request: Paid.OrderCreate,
        requestOptions?: Orders.RequestOptions,
    ): core.HttpResponsePromise<Paid.Order> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Paid.OrderCreate,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.Order>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                "orders",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Order, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PaidError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling POST /orders.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} orderId
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.orders.get("orderId")
     */
    public get(orderId: string, requestOptions?: Orders.RequestOptions): core.HttpResponsePromise<Paid.Order> {
        return core.HttpResponsePromise.fromPromise(this.__get(orderId, requestOptions));
    }

    private async __get(
        orderId: string,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.Order>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Order, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PaidError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling GET /orders/{orderId}.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} orderId
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.orders.delete("orderId")
     */
    public delete(orderId: string, requestOptions?: Orders.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(orderId, requestOptions));
    }

    private async __delete(
        orderId: string,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}`,
            ),
            method: "DELETE",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PaidError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling DELETE /orders/{orderId}.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} orderId
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.orders.activate("orderId")
     */
    public activate(orderId: string, requestOptions?: Orders.RequestOptions): core.HttpResponsePromise<Paid.Order> {
        return core.HttpResponsePromise.fromPromise(this.__activate(orderId, requestOptions));
    }

    private async __activate(
        orderId: string,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.Order>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}/activate`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Order, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PaidError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling POST /orders/{orderId}/activate.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Activates the order and processes the initial payment using the provided Stripe confirmation token.
     *
     * @param {string} orderId - The order ID (can be internal ID or display ID)
     * @param {Paid.OrdersActivateAndPayRequest} request
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.BadRequestError}
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.NotFoundError}
     *
     * @example
     *     await client.orders.activateAndPay("orderId", {
     *         confirmationToken: "ctoken_1234567890",
     *         returnUrl: "https://example.com/payment-complete"
     *     })
     */
    public activateAndPay(
        orderId: string,
        request: Paid.OrdersActivateAndPayRequest,
        requestOptions?: Orders.RequestOptions,
    ): core.HttpResponsePromise<Paid.Order> {
        return core.HttpResponsePromise.fromPromise(this.__activateAndPay(orderId, request, requestOptions));
    }

    private async __activateAndPay(
        orderId: string,
        request: Paid.OrdersActivateAndPayRequest,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.Order>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}/activate-and-pay`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Order, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Paid.BadRequestError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as Paid.Error_, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError(
                    "Timeout exceeded when calling POST /orders/{orderId}/activate-and-pay.",
                );
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Schedules the cancellation of an order's renewal from a specified date. The order will remain active until the cancellation date.
     *
     * @param {string} orderId - The order ID (can be internal ID or display ID)
     * @param {Paid.CancelRenewalRequest} request
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.BadRequestError}
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.NotFoundError}
     *
     * @example
     *     await client.orders.cancelRenewal("orderId", {
     *         orderVersion: 1,
     *         cancelFromDate: "2025-12-31T00:00:00Z"
     *     })
     */
    public cancelRenewal(
        orderId: string,
        request: Paid.CancelRenewalRequest,
        requestOptions?: Orders.RequestOptions,
    ): core.HttpResponsePromise<Paid.CancelRenewalResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancelRenewal(orderId, request, requestOptions));
    }

    private async __cancelRenewal(
        orderId: string,
        request: Paid.CancelRenewalRequest,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.CancelRenewalResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}/cancel`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.CancelRenewalResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Paid.BadRequestError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as Paid.Error_, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling POST /orders/{orderId}/cancel.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Schedules a plan upgrade or downgrade for an order with automatic proration calculation. Credits are applied for the unused portion of the current billing period.
     *
     * @param {string} orderId - The order ID (can be internal ID or display ID)
     * @param {Paid.ProrationUpgradeRequest} request
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.BadRequestError}
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.NotFoundError}
     *
     * @example
     *     await client.orders.schedulePlanChange("orderId", {
     *         orderVersion: 1,
     *         effectiveDate: "2025-02-01T00:00:00Z",
     *         updatedOrderLineAttributes: [{
     *                 orderLineAttributeId: "a1b2c3d4-5678-90ab-cdef-1234567890ab",
     *                 newPricing: {
     *                     "unitPrice": 200,
     *                     "currency": "USD"
     *                 },
     *                 newQuantity: 10
     *             }]
     *     })
     */
    public schedulePlanChange(
        orderId: string,
        request: Paid.ProrationUpgradeRequest,
        requestOptions?: Orders.RequestOptions,
    ): core.HttpResponsePromise<Paid.ProrationUpgradeResponse> {
        return core.HttpResponsePromise.fromPromise(this.__schedulePlanChange(orderId, request, requestOptions));
    }

    private async __schedulePlanChange(
        orderId: string,
        request: Paid.ProrationUpgradeRequest,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.ProrationUpgradeResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}/schedule-plan-change`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.ProrationUpgradeResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Paid.BadRequestError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as Paid.Error_, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError(
                    "Timeout exceeded when calling POST /orders/{orderId}/schedule-plan-change.",
                );
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieves all invoices associated with a specific order.
     *
     * @param {string} orderId - The order ID (can be internal ID or display ID)
     * @param {Orders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.NotFoundError}
     *
     * @example
     *     await client.orders.getInvoices("orderId")
     */
    public getInvoices(
        orderId: string,
        requestOptions?: Orders.RequestOptions,
    ): core.HttpResponsePromise<Paid.Invoice[]> {
        return core.HttpResponsePromise.fromPromise(this.__getInvoices(orderId, requestOptions));
    }

    private async __getInvoices(
        orderId: string,
        requestOptions?: Orders.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.Invoice[]>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Production,
                `orders/${encodeURIComponent(orderId)}/invoices`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Invoice[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.Error_, _response.rawResponse);
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as Paid.Error_, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling GET /orders/{orderId}/invoices.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
