/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         description: "description"
 *     }
 */
export interface AgentCreate {
    name: string;
    description: string;
    agentCode?: string;
    externalId?: string;
}
