/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Acme Agent",
 *         description: "Acme Agent is an AI agent that does things.",
 *         externalId: "acme-agent"
 *     }
 */
export interface AgentCreate {
    name: string;
    description: string;
    agentCode?: string;
    externalId?: string;
    active?: boolean;
}
