/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         externalCustomerId: "acme-inc",
 *         externalProductId: "acme-agent"
 *     }
 *
 * @example
 *     {
 *         externalCustomerId: "acme-inc",
 *         externalProductId: "acme-agent"
 *     }
 *
 * @example
 *     {
 *         externalCustomerId: "acme-inc",
 *         externalProductId: "acme-agent"
 *     }
 */
export interface UsageCheckUsageRequest {
    /** External customer ID */
    externalCustomerId: string;
    /** External product ID to check usage for */
    externalProductId: string;
}
