// This file was auto-generated by Fern from our API Definition.

export const ListValueReceiptsRequestArchived = {
    True: "true",
    False: "false",
} as const;
export type ListValueReceiptsRequestArchived =
    (typeof ListValueReceiptsRequestArchived)[keyof typeof ListValueReceiptsRequestArchived];
