/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Paid from "../index.js";

export interface AgentUpdate {
    name?: string;
    description?: string;
    externalId?: string;
    active?: boolean;
    agentCode?: string;
    agentAttributes?: Paid.AgentAttribute[];
}
