// This file was auto-generated by Fern from our API Definition.

/** Charge type. */
export const AmendmentChargeType = {
    Usage: "usage",
    Recurring: "recurring",
    OneTime: "oneTime",
    SeatBased: "seatBased",
} as const;
export type AmendmentChargeType = (typeof AmendmentChargeType)[keyof typeof AmendmentChargeType];
