// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

/**
 * One applicability clause. Match every non-empty list. Empty lists constrain nothing.
 */
export interface AmendmentPricingClause {
    /** Charge types this clause matches. Empty matches any. */
    chargeTypes?: Paid.AmendmentChargeType[];
    /** Billing types this clause matches. Empty matches any. */
    billingTypes?: Paid.AmendmentBillingType[];
    /** Pricing models this clause matches. Empty matches any. */
    pricingModels?: Paid.AmendmentPricingModel[];
    /** Accepts any additional properties */
    [key: string]: any;
}
