// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface AmendmentPlanCreditEffect {
    /** Index of the request intent that produced this entry. */
    intentIndex: number;
    kind: Paid.AmendmentCreditEffectKind;
    orderLineAttributeId?: string;
    /** When the effect applies. */
    at: string;
    /** Credits ended or granted. Absent for infinite benefits. */
    creditAmount?: number;
    /** True when the affected benefit is unlimited. */
    hasInfiniteCredits?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}
