// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export type AmendmentAddAxisOptions =
    | Paid.AmendmentAddAxisOptions.ChargeStub
    | Paid.AmendmentAddAxisOptions.CreditGrant;

export namespace AmendmentAddAxisOptions {
    export interface ChargeStub extends Paid.ChargeStubAddAxisOptions {
        axis: "chargeStub";
    }

    export interface CreditGrant extends Paid.CreditGrantAddAxisOptions {
        axis: "creditGrant";
    }
}
