// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface AmendmentLineOptions {
    /** Line UUID. Pass this on `updateLineTerm`. */
    orderLineId: string;
    attributes: Paid.AmendmentAttributeOptions[];
    /** Line-level intents, such as `updateLineTerm`. */
    intents?: Paid.AmendmentIntentOptions[];
    /** Set when this line cannot be amended. */
    lockedReason?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
