// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface AmendmentPlanTreatmentResolution {
    /** Index of the request intent that produced this entry. */
    intentIndex: number;
    axis: Paid.AmendmentAxisId;
    value: Paid.AmendmentAxisChoiceValue;
    source: Paid.AmendmentTreatmentSource;
    /** Human-readable explanation of why this value was chosen. */
    reason: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
