// This file was auto-generated by Fern from our API Definition.

/** When the charge is billed. Wire values are PascalCase. */
export const AmendmentBillingType = {
    Advance: "Advance",
    Arrears: "Arrears",
} as const;
export type AmendmentBillingType = (typeof AmendmentBillingType)[keyof typeof AmendmentBillingType];
