// This file was auto-generated by Fern from our API Definition.

/** STANDARD is a caller-intended add. PRORATION lines are amendment-computed settlement. */
export const AmendmentPlanLineType = {
    Standard: "STANDARD",
    ProrationCredit: "PRORATION_CREDIT",
    ProrationCharge: "PRORATION_CHARGE",
    Credit: "CREDIT",
} as const;
export type AmendmentPlanLineType = (typeof AmendmentPlanLineType)[keyof typeof AmendmentPlanLineType];
