// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsQueryRequest {
    /** A single ClickHouse SELECT (or WITH ... SELECT) statement against the analytics views. Results are automatically scoped to your organization. See GET /schema for the available views and columns. */
    query: string;
}
