// This file was auto-generated by Fern from our API Definition.

/**
 * An API error response from the Paid API
 */
export interface ApiError {
    /** A human-readable message providing more details about the error. */
    message?: string;
    code?: string;
    details?: string;
}
