/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BillingFrequency = "Monthly" | "Quarterly" | "Annual";
export const BillingFrequency = {
    Monthly: "Monthly",
    Quarterly: "Quarterly",
    Annual: "Annual",
} as const;
