// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface ChargeStubAxisOptions {
    relevance: Paid.AmendmentAxisRelevance;
    options: ChargeStubAxisOptions.Options.Item[];
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace ChargeStubAxisOptions {
    export type Options = Options.Item[];

    export namespace Options {
        export interface Item {
            /** How to charge the partial first period when adding an attribute mid-cycle. */
            value: Item.Value;
            /** True when this is the value used if you omit the choice. */
            isDefault: boolean;
            /** False when this option cannot be chosen for this intent. */
            available: boolean;
            /** Why the option is unavailable, when `available` is false. */
            unavailableReason?: string;
            /** Accepts any additional properties */
            [key: string]: any;
        }

        export namespace Item {
            /** How to charge the partial first period when adding an attribute mid-cycle. */
            export const Value = {
                None: "none",
                Prorated: "prorated",
                Full: "full",
            } as const;
            export type Value = (typeof Value)[keyof typeof Value];
        }
    }
}
