/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChargeType = "oneTime" | "recurring" | "usage" | "seatBased";
export const ChargeType = {
    OneTime: "oneTime",
    Recurring: "recurring",
    Usage: "usage",
    SeatBased: "seatBased",
} as const;
