// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CheckoutProduct {
    id: string;
    /** Plans selected within this product. Absent when the product is offered with all of its plans and none are individually configured. */
    plans?: Paid.CheckoutPlan[];
}
