// This file was auto-generated by Fern from our API Definition.

export interface CheckoutSessionDetails {
    id: string;
    token: string;
    status: CheckoutSessionDetails.Status;
    product: CheckoutSessionDetails.Product;
    customer: CheckoutSessionDetails.Customer;
    success_url: string;
    cancel_url: string;
    metadata?: Record<string, unknown> | null;
    expires_at: string;
    completed_at?: string | null;
    created_at: string;
}

export namespace CheckoutSessionDetails {
    export const Status = {
        Pending: "pending",
        Completed: "completed",
        Expired: "expired",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Product {
        id?: string;
        name?: string;
        description?: string | null;
    }

    export interface Customer {
        id?: string;
        name?: string;
        email?: string;
        externalId?: string | null;
    }
}
