// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CheckoutProductInput {
    id: string;
    /** Select specific plans within this product. Omit to offer all of the product's plans. */
    plans?: Paid.CheckoutPlanInput[];
}
