// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface Contact {
    id: string;
    customerId: string;
    firstName: string;
    lastName: string;
    email: string;
    phone: string | null;
    billingAddress?: Paid.ContactBillingAddress | null;
    externalId: string | null;
    roles: Contact.Roles.Item[];
    createdAt: string;
    updatedAt: string;
}

export namespace Contact {
    export type Roles = Roles.Item[];

    export namespace Roles {
        export const Item = {
            Billing: "BILLING",
            AccountsPayable: "ACCOUNTS_PAYABLE",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
