// This file was auto-generated by Fern from our API Definition.

export interface CostIngestResponse {
    /** Number of records persisted. */
    ingested: number;
    /** Number of records skipped because their `idempotencyKey` matched a previously ingested record. */
    duplicates: number;
}
