/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Paid from "../index.js";

/**
 * Response containing cost traces and pagination metadata
 */
export interface CostTracesResponse {
    traces: Paid.CostTrace[];
    meta: Paid.PaginationMeta;
}
