// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export type Cost = Paid.Cost.Cost | Paid.Cost.Usage;

export namespace Cost {
    export interface Cost extends Paid.PrecomputedCost {
        type: "cost";
    }

    export interface Usage extends Paid.UsageCost {
        type: "usage";
    }
}
