// This file was auto-generated by Fern from our API Definition.

/**
 * If supplied, overrides server-side pricing. The usage breakdown is still recorded for analytics.
 */
export interface CostOverride {
    amount: number;
    /** ISO 4217 currency code, e.g. "USD". */
    currency: string;
}
