/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Paid from "../index.js";

/**
 * A single cost trace record
 */
export interface CostTrace {
    /** The name/type of the operation (e.g., "trace.openai.agents.on_agent") */
    name: string;
    /** The vendor/provider (e.g., "openai", "anthropic", "mistral") */
    vendor: string;
    cost: Paid.CostAmount;
    /** Unix timestamp in nanoseconds when the operation started */
    startTimeUnixNano: string;
    /** Unix timestamp in nanoseconds when the operation completed */
    endTimeUnixNano: string;
    /** Additional metadata about the trace (e.g., model, tokens, etc.) */
    attributes: Record<string, unknown>;
}
