// This file was auto-generated by Fern from our API Definition.

export const CreationState = {
    Active: "active",
    Draft: "draft",
} as const;
export type CreationState = (typeof CreationState)[keyof typeof CreationState];
