// This file was auto-generated by Fern from our API Definition.

export interface CreditCurrency {
    /** Unique identifier for this credit currency. */
    id: string;
    /** Human-readable name shown for this credit currency. */
    name: string;
    /** Stable machine-readable key for this credit currency. Keys are unique within an organization. */
    key: string;
    /** Whether this credit currency is active or archived. */
    status: CreditCurrency.Status;
    /** Optional description for this credit currency. */
    description: string | null;
    /** When this credit currency was archived. Null means the currency is active. */
    archivedAt: string | null;
    /** When this credit currency was created. */
    createdAt: string;
    /** When this credit currency was last updated. */
    updatedAt: string;
}

export namespace CreditCurrency {
    /** Whether this credit currency is active or archived. */
    export const Status = {
        Active: "active",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
