// This file was auto-generated by Fern from our API Definition.

export interface CreditTransactionCurrency {
    /** Stable machine-readable key for this credit currency. */
    key: string;
    /** Human-readable name for this credit currency. */
    name: string;
}
