// This file was auto-generated by Fern from our API Definition.

export interface CreditBalance {
    creditsCurrencyId: string;
    currencyName: string;
    currencyKey: string;
    available: number;
    used: number;
    total: number;
    periodStart: string | null;
    periodEnd: string | null;
    rolloverEndDate: string | null;
    recipient: CreditBalance.Recipient;
}

export namespace CreditBalance {
    export const Recipient = {
        Organization: "organization",
        Seat: "seat",
    } as const;
    export type Recipient = (typeof Recipient)[keyof typeof Recipient];
}
