// This file was auto-generated by Fern from our API Definition.

export interface CustomerUnit {
    /** Your own id for the unit, unique within the customer; the identifier every unit route takes. */
    externalId: string;
    /** Display name. Never used to address the unit. */
    name: string;
    /** Your structural vocabulary for the unit. */
    externalType: string | null;
    /** ACTIVE, or DELETED after a soft delete (one-way). */
    status: CustomerUnit.Status;
    /** `externalId` of the parent unit; `null` only on the customer's root unit. */
    parentExternalId: string | null;
    /** Whether this unit is the customer's root: the one unit without a parent. Derived from the missing parent, not stored. At most one active root per customer; the root cannot be moved, and once deleted a new root can be created. */
    isRoot: boolean;
    metadata: Record<string, unknown> | null;
    createdAt: string;
    updatedAt: string;
}

export namespace CustomerUnit {
    /** ACTIVE, or DELETED after a soft delete (one-way). */
    export const Status = {
        Active: "ACTIVE",
        Deleted: "DELETED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
