// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CustomerUser {
    id: string;
    externalId: string;
    customerExternalId: string;
    name: string | null;
    email: string | null;
    metadata: Record<string, unknown> | null;
    status: Paid.CustomerUserStatus;
    created: boolean;
    createdAt: string;
    updatedAt: string;
}
