// This file was auto-generated by Fern from our API Definition.

export interface CustomerStateCheckoutLink {
    id: string;
    url: string;
    status: CustomerStateCheckoutLink.Status;
    productIds: string[];
    singleUse: boolean;
    allowedCurrencies: string[];
    expiresAt: string | null;
}

export namespace CustomerStateCheckoutLink {
    export const Status = {
        Active: "active",
        Completed: "completed",
        Expired: "expired",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
