// This file was auto-generated by Fern from our API Definition.

/**
 * The cap version that was in force at the time of the call, now ended (`effectiveUntil` set). `null` when no version was in force — only scheduled versions were ended.
 */
export interface CustomerUnitCapEndedPolicy {
    /** The cap, in credits of the currency. JSON number; exact within ±2^53. */
    amount: number;
    /** Period length. Periods start on the day-of-month of `effectiveFrom` (UTC), clamped in shorter months. */
    frequency: CustomerUnitCapEndedPolicy.Frequency;
    /** When this cap version started applying, and the anchor for its periods. */
    effectiveFrom: string;
    /** When this cap version stopped applying (exclusive). */
    effectiveUntil: string;
    /** When this cap version was set. */
    createdAt: string;
    /** Where this cap version was set from. */
    source: string;
}

export namespace CustomerUnitCapEndedPolicy {
    /** Period length. Periods start on the day-of-month of `effectiveFrom` (UTC), clamped in shorter months. */
    export const Frequency = {
        Monthly: "MONTHLY",
    } as const;
    export type Frequency = (typeof Frequency)[keyof typeof Frequency];
}
