/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PaidApi from "../index.js";

export interface Customer {
    id: string;
    organizationId: string;
    name: string;
    externalId?: string;
    phone?: string;
    employeeCount?: number;
    annualRevenue?: number;
    taxExemptStatus?: PaidApi.TaxExemptStatus;
    creationSource?: PaidApi.CreationSource;
    creationState?: PaidApi.CreationState;
    website?: string;
    billingAddress?: PaidApi.Address;
}
