// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CustomerPortal {
    id: string;
    customerId: string;
    url: string;
    status: Paid.CustomerPortalStatus;
    returnUrl: string | null;
    expiresAt: string;
    createdAt: string;
}
