// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CustomerStateCustomer {
    /** Stable Paid customer display ID. Use this value as the `{id}` path parameter for customer routes, for example `GET /api/v2/customers/cus_abc123/state`. */
    id: string;
    name: string;
    externalId: string | null;
    billingAddress: Paid.CustomerBillingAddressResponse | null;
}
