// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface Customer {
    id: string;
    organizationId: string;
    name: string;
    externalId?: string;
    phone?: string;
    employeeCount?: number;
    annualRevenue?: number;
    taxExemptStatus?: Paid.TaxExemptStatus;
    creationSource?: Paid.CreationSource;
    creationState?: Paid.CreationState;
    website?: string;
    billingAddress?: Paid.Address;
    /** Flexible JSON field for storing custom metadata about the customer */
    metadata?: Record<string, unknown>;
}
