// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CustomViewAuthoringDetail {
    displayId: string;
    name: string;
    description: string | null;
    status: CustomViewAuthoringDetail.Status;
    /** Ids of the result sets the render bundle will receive. */
    queryIds: string[];
    /** Self-contained HTML document rendered inside the isolated sandbox iframe. */
    renderBundle: string;
    /** The view's current default date range, or null if it uses no adjustable period. */
    period: CustomViewAuthoringDetail.Period | null;
    /** The filter parameters this view accepts per request (pass values as `filter_<name>` query params on the data endpoint), or null if it declares none. Embedding hosts can render controls from the declared values. */
    filters: Paid.CustomViewFilter[] | null;
    /** 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only. */
    scope: CustomViewAuthoringDetail.Scope;
    queries: Paid.CustomViewQuery[];
    createdBy: string;
    createdAt: string;
    updatedAt: string;
    schemaVersion: number;
    /** The authoring guide (only when includeGuide=true) — same content as getCustomViewAuthoringGuide, returned inline to save a round trip. */
    guide?: string;
    /** The render-bundle template (only when includeGuide=true). */
    sampleBundle?: string;
}

export namespace CustomViewAuthoringDetail {
    export const Status = {
        Draft: "DRAFT",
        Published: "PUBLISHED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * The view's current default date range, or null if it uses no adjustable period.
     */
    export interface Period {
        /** 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`). */
        kind: Period.Kind;
        /** relative only: the unit of the rolling window. */
        unit?: Period.Unit;
        /** relative only: how many units back from today (e.g. unit 'day', amount 30 = last 30 days). */
        amount?: number;
        /** absolute only: inclusive start date (YYYY-MM-DD). */
        start?: string;
        /** absolute only: inclusive end date (YYYY-MM-DD). */
        end?: string;
    }

    export namespace Period {
        /** 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`). */
        export const Kind = {
            Relative: "relative",
            Absolute: "absolute",
        } as const;
        export type Kind = (typeof Kind)[keyof typeof Kind];
        /** relative only: the unit of the rolling window. */
        export const Unit = {
            Day: "day",
            Month: "month",
            Year: "year",
        } as const;
        export type Unit = (typeof Unit)[keyof typeof Unit];
    }

    /** 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only. */
    export const Scope = {
        Customer: "customer",
        Organization: "organization",
    } as const;
    export type Scope = (typeof Scope)[keyof typeof Scope];
}
