// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface Customer {
    id: string;
    name: string;
    legalName: string | null;
    email: string;
    phone: string;
    website: string;
    externalId: string | null;
    billingAddress?: Paid.CustomerBillingAddress | null;
    creationState: Paid.CustomerCreationState;
    churnDate: string | null;
    vatNumber: string | null;
    metadata: Record<string, unknown> | null;
    defaultCurrency: string;
    createdAt: string;
    updatedAt: string;
}
