/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PaidApi from "../index.js";

export interface CustomerUpdate {
    name?: string;
    externalId?: string;
    phone?: string;
    employeeCount?: number;
    annualRevenue?: number;
    taxExemptStatus?: PaidApi.TaxExemptStatus;
    creationSource?: PaidApi.CreationSource;
    website?: string;
    billingAddress?: PaidApi.Address;
}
