// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface CustomerUnitCapEndResponse {
    /** Your own id for the unit (its `externalId`), the identifier the unit and cap routes take. */
    externalCustomerUnitId: string;
    /** The Paid display id of the customer the unit belongs to. */
    customerId: string;
    /** The credits currency this cap limits. The cap's `amount` is in this currency's credits. */
    creditsCurrencyId: string;
    policy: Paid.CustomerUnitCapEndedPolicy | null;
    /** How many versions were closed by this call: the one in force, older overlapping versions still open, and scheduled versions. At least 1. */
    endedVersions: number;
}
