// This file was auto-generated by Fern from our API Definition.

export interface InvoiceLine {
    id: string;
    orderId: string | null;
    orderLineId: string | null;
    orderLineAttributeId: string | null;
    startDate: string;
    endDate: string;
    paymentStatus: InvoiceLine.PaymentStatus;
    quantity: number;
    totalPriceBeforeTax: number;
    tax: number;
    taxRate: number;
    totalPriceAfterTax: number;
    currency: string;
    description: string;
    balanceAmount: number;
    creditedAmount: number;
    createdAt: string;
    updatedAt: string;
}

export namespace InvoiceLine {
    export const PaymentStatus = {
        Pending: "pending",
        Paid: "paid",
        PartiallyPaid: "partiallyPaid",
        Overdue: "overdue",
        Error: "error",
    } as const;
    export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];
}
