// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface OneTimePerUnitInput {
    feeType?: OneTimePerUnitInput.FeeType;
    billingType?: OneTimePerUnitInput.BillingType;
    pricePoints: Paid.SimplePricePoint[];
}

export namespace OneTimePerUnitInput {
    export const FeeType = {
        Setup: "setup",
        Onboarding: "onboarding",
        Implementation: "implementation",
        Migration: "migration",
        Custom: "custom",
    } as const;
    export type FeeType = (typeof FeeType)[keyof typeof FeeType];
    export const BillingType = {
        Advance: "Advance",
        Arrears: "Arrears",
    } as const;
    export type BillingType = (typeof BillingType)[keyof typeof BillingType];
}
