// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface OrderListResponse {
    data: Paid.Order[];
    pagination: Paid.Pagination;
}
