// This file was auto-generated by Fern from our API Definition.

export interface OrderBillingFrequencyOverride {
    frequency: OrderBillingFrequencyOverride.Frequency;
    customMonths?: number | null;
}

export namespace OrderBillingFrequencyOverride {
    export const Frequency = {
        Monthly: "monthly",
        Quarterly: "quarterly",
        SemiAnnually: "semiAnnually",
        Annual: "annual",
        Custom: "custom",
    } as const;
    export type Frequency = (typeof Frequency)[keyof typeof Frequency];
}
