// This file was auto-generated by Fern from our API Definition.

export const OrderCreationState = {
    Draft: "draft",
    Active: "active",
} as const;
export type OrderCreationState = (typeof OrderCreationState)[keyof typeof OrderCreationState];
