/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PaidApi from "../index.js";

export interface Order {
    id?: string;
    name?: string;
    description?: string;
    customerId?: string;
    organizationId?: string;
    startDate?: string;
    endDate?: string;
    totalAmount?: number;
    estimatedTax?: number;
    billedAmountNoTax?: number;
    billedTax?: number;
    totalBilledAmount?: number;
    pendingBillingAmount?: number;
    creationState?: PaidApi.CreationState;
    orderLines?: PaidApi.OrderLine[];
    customer?: PaidApi.Customer;
}
