/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PaidApi from "../index.js";

export interface OrderLine {
    id?: string;
    orderId?: string;
    agentId?: string;
    name?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    totalAmount?: number;
    billedAmountWithoutTax?: number;
    billedTax?: number;
    totalBilledAmount?: number;
    creationState?: PaidApi.CreationState;
    agent?: PaidApi.Agent;
    orderLineAttributes?: PaidApi.OrderLineAttribute[];
}
