/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Pagination metadata for cost traces
 */
export interface PaginationMeta {
    /** The requested limit */
    limit: number;
    /** The requested offset */
    offset: number;
    /** Number of items returned in this response */
    count: number;
    /** Whether there are more results available */
    hasMore: boolean;
    /** The startTime filter that was applied (if any) */
    startTime?: string;
    /** The endTime filter that was applied (if any) */
    endTime?: string;
}
