/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A customer's payment method
 */
export interface PaymentMethod {
    /** The payment method ID (typically from Stripe) */
    id?: string;
    /** The type of payment method */
    type?: PaymentMethod.Type;
    /** Card details (present when type is 'card') */
    card?: PaymentMethod.Card;
    /** US bank account details (present when type is 'us_bank_account') */
    usBankAccount?: PaymentMethod.UsBankAccount;
    /** Whether this is the customer's default payment method */
    isDefault?: boolean;
    createdAt?: string;
}

export namespace PaymentMethod {
    /**
     * The type of payment method
     */
    export type Type = "card" | "us_bank_account" | "sepa_debit";
    export const Type = {
        Card: "card",
        UsBankAccount: "us_bank_account",
        SepaDebit: "sepa_debit",
    } as const;

    /**
     * Card details (present when type is 'card')
     */
    export interface Card {
        /** Card brand (visa, mastercard, amex, etc.) */
        brand?: string;
        /** Last 4 digits of the card number */
        last4?: string;
        /** Expiration month (1-12) */
        expMonth?: number;
        /** Expiration year */
        expYear?: number;
    }

    /**
     * US bank account details (present when type is 'us_bank_account')
     */
    export interface UsBankAccount {
        bankName?: string;
        /** Last 4 digits of the account number */
        last4?: string;
        accountType?: UsBankAccount.AccountType;
    }

    export namespace UsBankAccount {
        export type AccountType = "checking" | "savings";
        export const AccountType = {
            Checking: "checking",
            Savings: "savings",
        } as const;
    }
}
