// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

/**
 * Structural writes the amendment executes.
 */
export interface PlannedOperations {
    ends?: Paid.PlannedEnd[];
    replaces?: Paid.PlannedReplace[];
    copies?: Paid.PlannedCopy[];
    adds?: Paid.PlannedAdd[];
    orderTerm?: Paid.PlannedOrderTerm;
    /** Accepts any additional properties */
    [key: string]: any;
}
