// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

/**
 * A plan with its features (product-attribute pairs) for display
 */
export interface PlanWithFeatures {
    /** The unique identifier of the plan */
    id: string;
    /** The name of the plan */
    name: string;
    /** The description of the plan */
    description?: string;
    /** The type of plan (flat for fixed pricing, usage for usage-based, credit for prepaid credits) */
    type: PlanWithFeatures.Type;
    pricing: Paid.PlanPricing;
    /** When the plan was created */
    createdAt: string;
    /** When the plan was last updated */
    updatedAt: string;
    /** The ID of the next plan in the sequence */
    nextPlanId?: string;
    /** The ID of the previous plan in the sequence */
    prevPlanId?: string;
    /** The features (product-attribute pairs) included in this plan */
    features: PlanWithFeatures.Features.Item[];
}

export namespace PlanWithFeatures {
    /** The type of plan (flat for fixed pricing, usage for usage-based, credit for prepaid credits) */
    export const Type = {
        Flat: "flat",
        Usage: "usage",
        Credit: "credit",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export type Features = Features.Item[];

    export namespace Features {
        export interface Item {
            /** The name of the product */
            productName: string;
            /** The name of the product attribute */
            attributeName: string;
            /** The pricing configuration for this feature */
            pricing: Record<string, unknown>;
        }
    }
}
