// This file was auto-generated by Fern from our API Definition.

export const PricingModelType = {
    PerUnit: "PerUnit",
    VolumePricing: "VolumePricing",
    GraduatedPricing: "GraduatedPricing",
    PrepaidCredits: "PrepaidCredits",
} as const;
export type PricingModelType = (typeof PricingModelType)[keyof typeof PricingModelType];
