// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export type PricingInput =
    | Paid.PricingInput.RecurringPerUnit
    | Paid.PricingInput.RecurringGraduated
    | Paid.PricingInput.RecurringVolume
    | Paid.PricingInput.RecurringPercentOfTotal
    | Paid.PricingInput.UsagePerUnit
    | Paid.PricingInput.UsageGraduated
    | Paid.PricingInput.UsageVolume
    | Paid.PricingInput.UsagePrepaidCredits
    | Paid.PricingInput.UsageCostPlus
    | Paid.PricingInput.OneTimePerUnit
    | Paid.PricingInput.SeatBasedPerUnit
    | Paid.PricingInput.SeatBasedGraduated
    | Paid.PricingInput.SeatBasedVolume
    | Paid.PricingInput.SeatBasedPrepaidCredits;

export namespace PricingInput {
    export interface RecurringPerUnit extends Paid.RecurringPerUnitInput {
        pricingType: "RecurringPerUnit";
    }

    export interface RecurringGraduated extends Paid.RecurringGraduatedInput {
        pricingType: "RecurringGraduated";
    }

    export interface RecurringVolume extends Paid.RecurringVolumeInput {
        pricingType: "RecurringVolume";
    }

    export interface RecurringPercentOfTotal extends Paid.RecurringPercentOfTotalInput {
        pricingType: "RecurringPercentOfTotal";
    }

    export interface UsagePerUnit extends Paid.UsagePerUnitInput {
        pricingType: "UsagePerUnit";
    }

    export interface UsageGraduated extends Paid.UsageGraduatedInput {
        pricingType: "UsageGraduated";
    }

    export interface UsageVolume extends Paid.UsageVolumeInput {
        pricingType: "UsageVolume";
    }

    export interface UsagePrepaidCredits extends Paid.UsagePrepaidCreditsInput {
        pricingType: "UsagePrepaidCredits";
    }

    export interface UsageCostPlus extends Paid.UsageCostPlusInput {
        pricingType: "UsageCostPlus";
    }

    export interface OneTimePerUnit extends Paid.OneTimePerUnitInput {
        pricingType: "OneTimePerUnit";
    }

    export interface SeatBasedPerUnit extends Paid.SeatBasedPerUnitInput {
        pricingType: "SeatBasedPerUnit";
    }

    export interface SeatBasedGraduated extends Paid.SeatBasedGraduatedInput {
        pricingType: "SeatBasedGraduated";
    }

    export interface SeatBasedVolume extends Paid.SeatBasedVolumeInput {
        pricingType: "SeatBasedVolume";
    }

    export interface SeatBasedPrepaidCredits extends Paid.SeatBasedPrepaidCreditsInput {
        pricingType: "SeatBasedPrepaidCredits";
    }
}
