// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface ProductAttributeUpsert {
    productAttributeId?: string;
    name: string;
    active?: boolean;
    pricing: Paid.ProductPricingInput;
    creditBenefits?: Paid.ProductCreditBenefitInput[];
    taxCode?: string | null;
}
