// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface ProductRecurringVolumeInput {
    billingFrequency: ProductRecurringVolumeInput.BillingFrequency;
    billingFrequencyCustomMonths?: number;
    billingType?: ProductRecurringVolumeInput.BillingType;
    pricePoints: Paid.ProductTieredPricePoint[];
}

export namespace ProductRecurringVolumeInput {
    export const BillingFrequency = {
        Monthly: "Monthly",
        Quarterly: "Quarterly",
        SemiAnnually: "Semi-Annually",
        Annual: "Annual",
        Custom: "Custom",
    } as const;
    export type BillingFrequency = (typeof BillingFrequency)[keyof typeof BillingFrequency];
    export const BillingType = {
        Advance: "Advance",
        Arrears: "Arrears",
    } as const;
    export type BillingType = (typeof BillingType)[keyof typeof BillingType];
}
