// This file was auto-generated by Fern from our API Definition.

export interface ProductPricingTierOutput {
    flatAmount?: number;
    index?: number;
    lowerBound: number;
    number?: number;
    tierBillingType?: ProductPricingTierOutput.TierBillingType;
    unitAmount?: number;
    upperBound?: number;
}

export namespace ProductPricingTierOutput {
    export const TierBillingType = {
        Flat: "flat",
        PerUnit: "perUnit",
    } as const;
    export type TierBillingType = (typeof TierBillingType)[keyof typeof TierBillingType];
}
