// This file was auto-generated by Fern from our API Definition.

/**
 * V2 signal schema with clean field names. IMPORTANT: Exactly one customer ID field (customer_id OR external_customer_id) and exactly one product ID field (product_id OR external_product_id) must be provided per signal.
 */
export interface SignalV2 {
    /** The name of the event being tracked */
    event_name: string;
    /** Paid's display ID for the product (e.g., prod_abc123). Cannot be used with external_product_id. Either this or external_product_id is required. */
    product_id?: string;
    /** Your system's product ID. Cannot be used with product_id. Either this or product_id is required. */
    external_product_id?: string;
    /** Paid's display ID for the customer (e.g., cus_xyz789). Cannot be used with external_customer_id. Either this or external_customer_id is required. */
    customer_id?: string;
    /** Your system's customer ID. Cannot be used with customer_id. Either this or customer_id is required. */
    external_customer_id?: string;
    /** Optional additional data/metadata for the signal */
    data?: Record<string, unknown>;
    /** A unique key to ensure idempotent signal processing */
    idempotency_key?: string;
}
