// This file was auto-generated by Fern from our API Definition.

export interface SignalListItem {
    /** Unique signal identifier. */
    id: string;
    /** Signal event name as submitted at ingest. */
    name: string;
    /** Paid customer ID the signal is attributed to, or null if unattributed. */
    customerId: string | null;
    /** The external customer ID recorded at ingest, including unresolved IDs, or null if not set. */
    externalCustomerId: string | null;
    /** Paid product ID the signal is attributed to, or null if unattributed. */
    productId: string | null;
    /** The external product ID recorded at ingest, including unresolved IDs, or null if not set. */
    externalProductId: string | null;
    /** Distributed trace ID, or null if none was recorded. */
    traceId: string | null;
    /** The data payload submitted with the signal. */
    data: Record<string, unknown> | null;
    /** When the signal was ingested (ISO 8601, UTC). */
    createdAt: string;
}
