// This file was auto-generated by Fern from our API Definition.

export interface TieredPricePoint {
    currency: string;
    unitPrice: number;
    tiers: TieredPricePoint.Tiers.Item[];
    minQuantity?: number;
    maxQuantity?: number;
    includedQuantity?: number;
}

export namespace TieredPricePoint {
    export type Tiers = Tiers.Item[];

    export namespace Tiers {
        export interface Item {
            flatAmount?: number;
            index?: number;
            lowerBound: number;
            number?: number;
            tierBillingType?: Item.TierBillingType;
            unitAmount?: number;
            upperBound?: number;
        }

        export namespace Item {
            export const TierBillingType = {
                Flat: "flat",
                PerUnit: "perUnit",
            } as const;
            export type TierBillingType = (typeof TierBillingType)[keyof typeof TierBillingType];
        }
    }
}
