// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

/**
 * Response containing cost traces and pagination metadata
 */
export interface TracesResponse {
    traces: Paid.Trace[];
    meta: Paid.PaginationMeta;
}
