// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

/**
 * A single cost trace record with customer and product info
 */
export interface Trace {
    /** The name/type of the operation (e.g., "trace.openai.agents.on_agent") */
    name: string;
    /** The vendor/provider (e.g., "openai", "anthropic", "mistral") */
    vendor: string;
    /** The model used for the operation (e.g., "gpt-4o-mini", "claude-3-sonnet") */
    model: string;
    cost: Paid.CostAmount;
    /** Unix timestamp in nanoseconds when the operation started */
    startTimeUnixNano: string;
    /** Unix timestamp in nanoseconds when the operation completed */
    endTimeUnixNano: string;
    /** Additional metadata about the trace (e.g., tokens, etc.) */
    attributes: Record<string, unknown>;
    /** The internal customer ID associated with this trace */
    customerId?: string;
    /** The product/agent ID associated with this trace (optional) */
    productId?: string;
}
