// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export type UnifiedAmendmentIntent =
    | Paid.UnifiedAmendmentIntent.UpdateQuantity
    | Paid.UnifiedAmendmentIntent.UpdatePricing
    | Paid.UnifiedAmendmentIntent.EndAttribute
    | Paid.UnifiedAmendmentIntent.AddFromCatalog
    | Paid.UnifiedAmendmentIntent.AddAttribute
    | Paid.UnifiedAmendmentIntent.UpdateLineTerm
    | Paid.UnifiedAmendmentIntent.UpdateOrderTerm;

export namespace UnifiedAmendmentIntent {
    export interface UpdateQuantity extends Paid.UpdateQuantityIntent {
        type: "updateQuantity";
    }

    export interface UpdatePricing extends Paid.UpdatePricingIntent {
        type: "updatePricing";
    }

    export interface EndAttribute extends Paid.EndAttributeIntent {
        type: "endAttribute";
    }

    export interface AddFromCatalog extends Paid.AddFromCatalogIntent {
        type: "addFromCatalog";
    }

    export interface AddAttribute extends Paid.AddAttributeIntent {
        type: "addAttribute";
    }

    export interface UpdateLineTerm extends Paid.UpdateLineTermIntent {
        type: "updateLineTerm";
    }

    export interface UpdateOrderTerm extends Paid.UpdateOrderTermIntent {
        type: "updateOrderTerm";
    }
}
