// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface UpdatePlanRequest {
    name?: string | null;
    externalId?: string | null;
    supportedCurrencies?: string[];
    isDefault?: boolean;
    /** Set to `archived` to archive this plan, or `active` to restore it. */
    status?: UpdatePlanRequest.Status;
    attributes?: Paid.PlanAttributeInput[];
}

export namespace UpdatePlanRequest {
    /** Set to `archived` to archive this plan, or `active` to restore it. */
    export const Status = {
        Active: "active",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
