// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface UpdateContactRequest {
    customerId?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string | null;
    billingAddress?: Paid.ContactBillingAddress | null;
    externalId?: string | null;
}
