// This file was auto-generated by Fern from our API Definition.

/**
 * A single usage summary record
 */
export interface UsageSummary {
    /** The unique identifier of the usage summary */
    id: string;
    /** The name of the event being tracked */
    eventName: string;
    /** The quantity of events in this usage period */
    eventsQuantity: number;
    /** The start date of the usage period */
    startDate: string;
    /** The end date of the usage period */
    endDate: string;
    /** The subtotal amount in the smallest currency unit (e.g., cents) */
    subtotal: number;
    /** The next billing date for this usage */
    nextBillingDate: string;
    /** The internal customer ID */
    customerId: string;
    /** The order ID associated with this usage */
    orderId: string;
    /** The order line ID associated with this usage */
    orderLineId: string;
    /** The order line attribute ID associated with this usage */
    orderLineAttributeId: string;
    /** The invoice ID if this usage has been invoiced */
    invoiceId?: string;
    /** The invoice line ID if this usage has been invoiced */
    invoiceLineId?: string;
    /** When the usage summary was created */
    createdAt: string;
    /** When the usage summary was last updated */
    updatedAt: string;
    /** Associated order information */
    order?: UsageSummary.Order;
    /** Associated order line information */
    orderLine?: UsageSummary.OrderLine;
}

export namespace UsageSummary {
    /**
     * Associated order information
     */
    export interface Order {
        id?: string;
        displayId?: string;
    }

    /**
     * Associated order line information
     */
    export interface OrderLine {
        id?: string;
        displayId?: string;
    }
}
