// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface UsagePerUnitInput {
    eventName: string;
    signalType?: UsagePerUnitInput.SignalType;
    billingFrequency?: UsagePerUnitInput.BillingFrequency;
    billingFrequencyCustomMonths?: number;
    billingType?: UsagePerUnitInput.BillingType;
    pricePoints: Paid.SimplePricePoint[];
}

export namespace UsagePerUnitInput {
    export const SignalType = {
        Activity: "activity",
        Outcome: "outcome",
    } as const;
    export type SignalType = (typeof SignalType)[keyof typeof SignalType];
    export const BillingFrequency = {
        Monthly: "Monthly",
        Quarterly: "Quarterly",
        SemiAnnually: "Semi-Annually",
        Annual: "Annual",
        Custom: "Custom",
    } as const;
    export type BillingFrequency = (typeof BillingFrequency)[keyof typeof BillingFrequency];
    export const BillingType = {
        Advance: "Advance",
        Arrears: "Arrears",
    } as const;
    export type BillingType = (typeof BillingType)[keyof typeof BillingType];
}
