// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface ValueMetricListResponse {
    data: Paid.ValueMetricSummary[];
    pagination: Paid.Pagination;
}
