// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../index.js";

export interface Webhook {
    id: string;
    name: Webhook.Name;
    description: string;
    enabled: boolean;
    url: string | null;
    lastSentAt: string | null;
    lastStatus: Paid.WebhookDeliveryStatus | null;
}

export namespace Webhook {
    export const Name = {
        BillingInvoiceCreated: "billing-invoice-created",
        BillingInvoicePaid: "billing-invoice-paid",
        BillingCheckoutCreated: "billing-checkout-created",
        BillingCheckoutCompleted: "billing-checkout-completed",
        BillingCheckoutExpired: "billing-checkout-expired",
        BillingPaymentSucceeded: "billing-payment-succeeded",
        BillingPaymentFailed: "billing-payment-failed",
        BillingCreditsDepleted: "billing-credits-depleted",
        BillingOverageIncurred: "billing-overage-incurred",
    } as const;
    export type Name = (typeof Name)[keyof typeof Name];
}
