// This file was auto-generated by Fern from our API Definition.

export const WebhookDeliveryStatus = {
    Success: "success",
    Failed: "failed",
} as const;
export type WebhookDeliveryStatus = (typeof WebhookDeliveryStatus)[keyof typeof WebhookDeliveryStatus];
