// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Paid from "../../../index.js";

export declare namespace Webhooks {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Webhooks {
    protected readonly _options: Webhooks.Options;

    constructor(_options: Webhooks.Options) {
        this._options = _options;
    }

    /**
     * List customer-facing billing webhooks for the authenticated organization.
     *
     * @param {Webhooks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.webhooks.listWebhooks()
     */
    public listWebhooks(requestOptions?: Webhooks.RequestOptions): core.HttpResponsePromise<Paid.WebhookListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listWebhooks(requestOptions));
    }

    private async __listWebhooks(
        requestOptions?: Webhooks.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.WebhookListResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                "webhooks/",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.WebhookListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(
                        _response.error.body as Paid.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling GET /webhooks/.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Enable or disable a webhook and configure the destination URL for the authenticated organization.
     *
     * @param {Paid.UpdateWebhookRequest} request
     * @param {Webhooks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.BadRequestError}
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.NotFoundError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.webhooks.updateWebhook({
     *         webhookName: "billing-invoice-created"
     *     })
     */
    public updateWebhook(
        request: Paid.UpdateWebhookRequest,
        requestOptions?: Webhooks.RequestOptions,
    ): core.HttpResponsePromise<Paid.Webhook> {
        return core.HttpResponsePromise.fromPromise(this.__updateWebhook(request, requestOptions));
    }

    private async __updateWebhook(
        request: Paid.UpdateWebhookRequest,
        requestOptions?: Webhooks.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.Webhook>> {
        const { webhookName, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                `webhooks/${core.url.encodePathParam(webhookName)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.Webhook, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Paid.BadRequestError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(
                        _response.error.body as Paid.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling PATCH /webhooks/{webhookName}.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Send a synthetic webhook delivery to the configured destination for this webhook.
     *
     * @param {Paid.TestWebhookRequest} request
     * @param {Webhooks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.BadRequestError}
     * @throws {@link Paid.ForbiddenError}
     * @throws {@link Paid.NotFoundError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.webhooks.testWebhook({
     *         webhookName: "billing-invoice-created"
     *     })
     */
    public testWebhook(
        request: Paid.TestWebhookRequest,
        requestOptions?: Webhooks.RequestOptions,
    ): core.HttpResponsePromise<Paid.WebhookTestResponse> {
        return core.HttpResponsePromise.fromPromise(this.__testWebhook(request, requestOptions));
    }

    private async __testWebhook(
        request: Paid.TestWebhookRequest,
        requestOptions?: Webhooks.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.WebhookTestResponse>> {
        const { webhookName, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                `webhooks/${core.url.encodePathParam(webhookName)}/test`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.WebhookTestResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Paid.BadRequestError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 403:
                    throw new Paid.ForbiddenError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as Paid.ErrorResponse, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(
                        _response.error.body as Paid.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling POST /webhooks/{webhookName}/test.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
