// This file was auto-generated by Fern from our API Definition.

export const ListCustomersRequestCreationState = {
    Draft: "draft",
    Active: "active",
} as const;
export type ListCustomersRequestCreationState =
    (typeof ListCustomersRequestCreationState)[keyof typeof ListCustomersRequestCreationState];
