// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateCustomerRequest {
    name: string;
    legalName?: string | null;
    email?: string;
    phone?: string;
    website?: string;
    externalId?: string | null;
    billingAddress?: Paid.CustomerBillingAddress | null;
    creationState?: Paid.CustomerCreationState;
    vatNumber?: string | null;
    metadata?: Record<string, unknown> | null;
}
