/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Acme, Inc.",
 *         externalId: "acme-inc"
 *     }
 */
export interface CustomerCreate {
    name: string;
    externalId?: string;
    phone?: string;
    employeeCount?: number;
    annualRevenue?: number;
    taxExemptStatus?: Paid.TaxExemptStatus;
    creationSource?: Paid.CreationSource;
    website?: string;
    billingAddress?: Paid.Address;
}
