// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         confirmationToken: "ctoken_1234567890",
 *         returnUrl: "https://example.com/payment-method-added",
 *         metadata: {
 *             "source": "api"
 *         }
 *     }
 */
export interface CustomersCreatePaymentMethodRequest {
    /** Stripe confirmation token for the payment method */
    confirmationToken: string;
    /** URL to redirect to after payment method setup */
    returnUrl: string;
    /** Optional metadata to attach to the payment method */
    metadata?: Record<string, unknown>;
}
