// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "cus_abc123"
 *     }
 */
export interface DeleteCustomerByIdRequest {
    /** Paid customer display id */
    id: string;
}
