// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "cus_abc123",
 *         alias: "child-customer-1"
 *     }
 */
export interface DeleteCustomerAliasRequest {
    /** Paid customer display id */
    id: string;
    /** Customer alias value. */
    alias: string;
}
