// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "cus_abc123",
 *         body: {
 *             creditCurrencyKey: "api_credits",
 *             amount: 10000,
 *             startsAt: "2026-06-05T12:00:00Z",
 *             expiresAt: "2026-12-31T23:59:59Z"
 *         }
 *     }
 */
export interface GrantCustomerCreditsRequest {
    /** Paid customer display id */
    id: string;
    body: Paid.CreditGrantCreateRequest;
}
