// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "cus_abc123",
 *         externalCustomerUnitId: "tenant-a",
 *         body: {
 *             amount: 10000
 *         }
 *     }
 */
export interface SetCustomerUnitCapRequest {
    /** Paid customer display id */
    id: string;
    /** Your own id for the unit (its `externalId`), unique within this customer. */
    externalCustomerUnitId: string;
    body: Paid.CustomerUnitCapSet;
}
