// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         externalId: "customer_123",
 *         externalCustomerUnitId: "team-research",
 *         body: {}
 *     }
 */
export interface UpdateCustomerUnitByExternalIdRequest {
    /** Customer ID from your system, stored on Paid as the customer's `externalId`. */
    externalId: string;
    /** Your own id for the unit (its `externalId`), unique within this customer. */
    externalCustomerUnitId: string;
    body: Paid.CustomerUnitUpdate;
}
