// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         externalId: "externalId",
 *         body: {}
 *     }
 */
export interface UpdateCustomerByExternalIdRequest {
    externalId: string;
    body: Paid.UpdateCustomerRequest;
}
