// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../../index.js";

/**
 * @example
 *     {
 *         customerExternalId: "customerExternalId",
 *         userExternalId: "userExternalId"
 *     }
 */
export interface UpsertCustomerUserRequest {
    customerExternalId: string;
    userExternalId: string;
    name?: string;
    email?: string | null;
    metadata?: Record<string, unknown> | null;
    status?: Paid.CustomerUserStatus;
}
