// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Paid from "../../../index.js";

export declare namespace ValueModels {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ValueModels {
    protected readonly _options: ValueModels.Options;

    constructor(_options: ValueModels.Options) {
        this._options = _options;
    }

    /**
     * Returns the current (latest active) value model for the organization.
     *
     * @param {ValueModels.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.NotFoundError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.valueModels.getCurrentValueModel()
     */
    public getCurrentValueModel(
        requestOptions?: ValueModels.RequestOptions,
    ): core.HttpResponsePromise<Paid.ValueModelDetail> {
        return core.HttpResponsePromise.fromPromise(this.__getCurrentValueModel(requestOptions));
    }

    private async __getCurrentValueModel(
        requestOptions?: ValueModels.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.ValueModelDetail>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                "value-models/",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.ValueModelDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling GET /value-models/.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Uploads a new value model version. Validates the content, creates a new version, archives the previous active version, syncs to ClickHouse, and triggers a backfill of all historical signals.
     *
     * @param {Paid.ValueModelUploadRequest} request
     * @param {ValueModels.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.BadRequestError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.valueModels.updateValueModel({
     *         content: {
     *             currency: "currency",
     *             valueTypes: [{
     *                     slug: "slug",
     *                     name: "name",
     *                     calculationTimeline: [{
     *                             effectiveFrom: "2024-01-15T09:30:00Z",
     *                             calculation: {
     *                                 unit: {
     *                                     type: "monetary"
     *                                 },
     *                                 formulaIds: ["formulaIds"],
     *                                 signalEventNames: ["signalEventNames"],
     *                                 segmentTableIds: ["segmentTableIds"],
     *                                 overrideIds: ["overrideIds"]
     *                             }
     *                         }]
     *                 }],
     *             formulas: [{
     *                     id: "id",
     *                     valueTypeSlug: "valueTypeSlug",
     *                     label: "label",
     *                     variables: [{
     *                             id: "id",
     *                             label: "label"
     *                         }],
     *                     expression: "expression"
     *                 }],
     *             signals: [{
     *                     eventName: "eventName",
     *                     label: "label"
     *                 }]
     *         }
     *     })
     */
    public updateValueModel(
        request: Paid.ValueModelUploadRequest,
        requestOptions?: ValueModels.RequestOptions,
    ): core.HttpResponsePromise<Paid.ValueModelDetail> {
        return core.HttpResponsePromise.fromPromise(this.__updateValueModel(request, requestOptions));
    }

    private async __updateValueModel(
        request: Paid.ValueModelUploadRequest,
        requestOptions?: ValueModels.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.ValueModelDetail>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                "value-models/",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.ValueModelDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Paid.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling PUT /value-models/.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns all value model versions sorted by version descending. Does not include the full content.
     *
     * @param {Paid.ListValueModelVersionsRequest} request
     * @param {ValueModels.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.valueModels.listValueModelVersions()
     */
    public listValueModelVersions(
        request: Paid.ListValueModelVersionsRequest = {},
        requestOptions?: ValueModels.RequestOptions,
    ): core.HttpResponsePromise<Paid.ValueModelVersionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listValueModelVersions(request, requestOptions));
    }

    private async __listValueModelVersions(
        request: Paid.ListValueModelVersionsRequest = {},
        requestOptions?: ValueModels.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.ValueModelVersionListResponse>> {
        const { limit, offset } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (offset != null) {
            _queryParams.offset = offset.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                "value-models/versions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.ValueModelVersionListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new Paid.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling GET /value-models/versions.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns a specific historical value model version by version number, including full content.
     *
     * @param {Paid.GetValueModelVersionRequest} request
     * @param {ValueModels.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.NotFoundError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.valueModels.getValueModelVersion({
     *         version: 1
     *     })
     */
    public getValueModelVersion(
        request: Paid.GetValueModelVersionRequest,
        requestOptions?: ValueModels.RequestOptions,
    ): core.HttpResponsePromise<Paid.ValueModelDetail> {
        return core.HttpResponsePromise.fromPromise(this.__getValueModelVersion(request, requestOptions));
    }

    private async __getValueModelVersion(
        request: Paid.GetValueModelVersionRequest,
        requestOptions?: ValueModels.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.ValueModelDetail>> {
        const { version } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                `value-models/versions/${core.url.encodePathParam(version)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.ValueModelDetail, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError(
                    "Timeout exceeded when calling GET /value-models/versions/{version}.",
                );
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Manually triggers a recalculation of all ClickHouse rows against the current value model.
     *
     * @param {Paid.RefreshValueModelBackfillRequest} request
     * @param {ValueModels.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Paid.NotFoundError}
     * @throws {@link Paid.InternalServerError}
     *
     * @example
     *     await client.valueModels.refreshValueModelBackfill()
     */
    public refreshValueModelBackfill(
        request: Paid.RefreshValueModelBackfillRequest = {},
        requestOptions?: ValueModels.RequestOptions,
    ): core.HttpResponsePromise<Paid.BackfillResponse> {
        return core.HttpResponsePromise.fromPromise(this.__refreshValueModelBackfill(request, requestOptions));
    }

    private async __refreshValueModelBackfill(
        request: Paid.RefreshValueModelBackfillRequest = {},
        requestOptions?: ValueModels.RequestOptions,
    ): Promise<core.WithRawResponse<Paid.BackfillResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PaidEnvironment.Default,
                "value-models/backfill",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Paid.BackfillResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Paid.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Paid.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PaidError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PaidError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PaidTimeoutError("Timeout exceeded when calling POST /value-models/backfill.");
            case "unknown":
                throw new errors.PaidError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
