/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         limit: 1,
 *         offset: 1,
 *         startTime: "2024-01-15T09:30:00Z",
 *         endTime: "2024-01-15T09:30:00Z",
 *         externalCustomerId: "externalCustomerId",
 *         externalAgentId: "externalAgentId",
 *         metadata: "metadata"
 *     }
 */
export interface GetTracesRequest {
    /**
     * Maximum number of traces to return (1-1000)
     */
    limit?: number;
    /**
     * Number of traces to skip for pagination
     */
    offset?: number;
    /**
     * Filter traces starting from this time (ISO 8601 format)
     */
    startTime?: string;
    /**
     * Filter traces up to this time (ISO 8601 format)
     */
    endTime?: string;
    /**
     * Filter traces by external customer ID
     */
    externalCustomerId?: string;
    /**
     * Filter traces by external agent ID
     */
    externalAgentId?: string;
    /**
     * Filter traces by metadata fields. Must be a valid JSON object (e.g., {"key1":"value1","key2":"value2"}). All specified fields must match (AND logic).
     */
    metadata?: string;
}
