// This file was auto-generated by Fern from our API Definition.

import type * as Paid from "../../../index.js";

export interface PlansGetCurrentResponse {
    /** The plan details, or null if the customer has no active plan */
    plan?: PlansGetCurrentResponse.Plan;
    /** The subscription details, or null if the customer has no active plan */
    subscription?: PlansGetCurrentResponse.Subscription;
}

export namespace PlansGetCurrentResponse {
    /**
     * The plan details, or null if the customer has no active plan
     */
    export interface Plan {
        /** The unique identifier of the plan */
        id: string;
        /** The name of the plan */
        name: string;
        /** The description of the plan */
        description?: string;
        /** The type of plan */
        type: Plan.Type;
        pricing: Paid.PlanPricing;
        /** The plan group ID this plan belongs to */
        planGroupId: string;
        /** The ID of the next plan in the sequence */
        nextPlanId?: string;
        /** The ID of the previous plan in the sequence */
        prevPlanId?: string;
        /** The features (product-attribute pairs) included in this plan with usage and limits */
        features: Plan.Features.Item[];
    }

    export namespace Plan {
        /** The type of plan */
        export const Type = {
            Flat: "flat",
            Usage: "usage",
            Credit: "credit",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
        export type Features = Features.Item[];

        export namespace Features {
            export interface Item {
                /** The name of the product */
                productName: string;
                /** The name of the product attribute */
                attributeName: string;
                /** The pricing configuration for this feature */
                pricing: Record<string, unknown>;
                /** Current usage and limits for this feature */
                usage: Item.Usage;
            }

            export namespace Item {
                /**
                 * Current usage and limits for this feature
                 */
                export interface Usage {
                    /** The event name used to track usage for this feature */
                    eventName?: string;
                    /** The current usage quantity for this feature on the order */
                    currentUsage: number;
                    /** The usage limit for this feature (null if unlimited) */
                    limit?: number;
                    /** Whether this feature has unlimited usage */
                    isUnlimited: boolean;
                }
            }
        }
    }

    /**
     * The subscription details, or null if the customer has no active plan
     */
    export interface Subscription {
        /** The ID of the order */
        orderId: string;
        /** The display ID of the order */
        orderDisplayId?: string;
        /** The start date of the subscription */
        startDate: string;
        /** The end date of the subscription (null if ongoing) */
        endDate?: string;
        /** The total usage quantity across all features on this order */
        totalUsage: number;
    }
}
