// This file was auto-generated by Fern from our API Definition.

export interface PlansGetCurrentResponse {
    plan: PlansGetCurrentResponse.Plan;
    subscription: PlansGetCurrentResponse.Subscription;
}

export namespace PlansGetCurrentResponse {
    export interface Plan {
        /** The unique identifier of the plan */
        id: string;
        /** The name of the plan */
        name: string;
        /** The description of the plan */
        description?: string;
        /** The type of plan */
        type: Plan.Type;
        /** The pricing configuration for the plan */
        pricing: Record<string, unknown>;
        /** The plan group ID this plan belongs to */
        planGroupId: string;
        /** The ID of the next plan in the sequence */
        nextPlanId?: string;
        /** The ID of the previous plan in the sequence */
        prevPlanId?: string;
        /** The features (product-attribute pairs) included in this plan */
        features: Plan.Features.Item[];
    }

    export namespace Plan {
        /** The type of plan */
        export const Type = {
            Flat: "flat",
            Usage: "usage",
            Credit: "credit",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
        export type Features = Features.Item[];

        export namespace Features {
            export interface Item {
                /** The name of the product */
                productName: string;
                /** The name of the product attribute */
                attributeName: string;
                /** The pricing configuration for this feature */
                pricing: Record<string, unknown>;
            }
        }
    }

    export interface Subscription {
        /** The ID of the order */
        orderId: string;
        /** The display ID of the order */
        orderDisplayId?: string;
        /** The start date of the subscription */
        startDate: string;
        /** The end date of the subscription (null if ongoing) */
        endDate?: string;
    }
}
