// This file was auto-generated by Fern from our API Definition.

import * as Paid from "../../src/api/index";
import { PaidClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Contacts", () => {
    test("listContacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    customerId: "customerId",
                    firstName: "firstName",
                    lastName: "lastName",
                    email: "email",
                    phone: "phone",
                    externalId: "externalId",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { limit: 1, offset: 1, total: 1, hasMore: true },
        };
        server.mockEndpoint().get("/contacts/").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.listContacts();
        expect(response).toEqual({
            data: [
                {
                    id: "id",
                    customerId: "customerId",
                    firstName: "firstName",
                    lastName: "lastName",
                    email: "email",
                    phone: "phone",
                    externalId: "externalId",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: {
                limit: 1,
                offset: 1,
                total: 1,
                hasMore: true,
            },
        });
    });

    test("listContacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts/").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("listContacts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts/").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("listContacts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts/").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("createContact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
        };
        const rawResponseBody = {
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: { street: "street", city: "city", state: "state", country: "country", zipCode: "zipCode" },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/contacts/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.createContact({
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
        });
        expect(response).toEqual({
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: {
                street: "street",
                city: "city",
                state: "state",
                country: "country",
                zipCode: "zipCode",
            },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("createContact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { customerId: "customerId", firstName: "x", lastName: "x", email: "email" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/contacts/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                customerId: "customerId",
                firstName: "x",
                lastName: "x",
                email: "email",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("createContact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { customerId: "customerId", firstName: "x", lastName: "x", email: "email" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/contacts/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                customerId: "customerId",
                firstName: "x",
                lastName: "x",
                email: "email",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("createContact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { customerId: "customerId", firstName: "x", lastName: "x", email: "email" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/contacts/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                customerId: "customerId",
                firstName: "x",
                lastName: "x",
                email: "email",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getContactById (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: { street: "street", city: "city", state: "state", country: "country", zipCode: "zipCode" },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server.mockEndpoint().get("/contacts/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.getContactById({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: {
                street: "street",
                city: "city",
                state: "state",
                country: "country",
                zipCode: "zipCode",
            },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("getContactById (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getContactById({
                id: "id",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("getContactById (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getContactById({
                id: "id",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getContactById (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.getContactById({
                id: "id",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("updateContactById (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: { street: "street", city: "city", state: "state", country: "country", zipCode: "zipCode" },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .put("/contacts/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.updateContactById({
            id: "id",
            body: {},
        });
        expect(response).toEqual({
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: {
                street: "street",
                city: "city",
                state: "state",
                country: "country",
                zipCode: "zipCode",
            },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("updateContactById (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactById({
                id: "id",
                body: {},
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("updateContactById (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactById({
                id: "id",
                body: {},
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("updateContactById (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactById({
                id: "id",
                body: {},
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("updateContactById (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactById({
                id: "id",
                body: {},
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("deleteContactById (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server.mockEndpoint().delete("/contacts/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.deleteContactById({
            id: "id",
        });
        expect(response).toEqual({});
    });

    test("deleteContactById (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().delete("/contacts/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.deleteContactById({
                id: "id",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("deleteContactById (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().delete("/contacts/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.deleteContactById({
                id: "id",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("deleteContactById (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().delete("/contacts/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.deleteContactById({
                id: "id",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getContactByExternalId (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: { street: "street", city: "city", state: "state", country: "country", zipCode: "zipCode" },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/contacts/external/externalId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getContactByExternalId({
            externalId: "externalId",
        });
        expect(response).toEqual({
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: {
                street: "street",
                city: "city",
                state: "state",
                country: "country",
                zipCode: "zipCode",
            },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("getContactByExternalId (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/contacts/external/externalId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactByExternalId({
                externalId: "externalId",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("getContactByExternalId (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/contacts/external/externalId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactByExternalId({
                externalId: "externalId",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getContactByExternalId (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/contacts/external/externalId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactByExternalId({
                externalId: "externalId",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("updateContactByExternalId (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: { street: "street", city: "city", state: "state", country: "country", zipCode: "zipCode" },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .put("/contacts/external/externalId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.updateContactByExternalId({
            externalId: "externalId",
            body: {},
        });
        expect(response).toEqual({
            id: "id",
            customerId: "customerId",
            firstName: "firstName",
            lastName: "lastName",
            email: "email",
            phone: "phone",
            billingAddress: {
                street: "street",
                city: "city",
                state: "state",
                country: "country",
                zipCode: "zipCode",
            },
            externalId: "externalId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("updateContactByExternalId (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/external/externalId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactByExternalId({
                externalId: "externalId",
                body: {},
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("updateContactByExternalId (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/external/externalId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactByExternalId({
                externalId: "externalId",
                body: {},
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("updateContactByExternalId (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/external/externalId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactByExternalId({
                externalId: "externalId",
                body: {},
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("updateContactByExternalId (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts/external/externalId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContactByExternalId({
                externalId: "externalId",
                body: {},
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("deleteContactByExternalId (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .delete("/contacts/external/externalId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.deleteContactByExternalId({
            externalId: "externalId",
        });
        expect(response).toEqual({});
    });

    test("deleteContactByExternalId (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .delete("/contacts/external/externalId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContactByExternalId({
                externalId: "externalId",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("deleteContactByExternalId (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .delete("/contacts/external/externalId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContactByExternalId({
                externalId: "externalId",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("deleteContactByExternalId (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .delete("/contacts/external/externalId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContactByExternalId({
                externalId: "externalId",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });
});
