// This file was auto-generated by Fern from our API Definition.

import * as Paid from "../../src/api/index";
import { PaidClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomViewsExperimental", () => {
    test("listCustomViews (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            views: [
                {
                    displayId: "displayId",
                    name: "name",
                    description: "description",
                    status: "DRAFT",
                    queryCount: 1,
                    period: { kind: "relative", start: "2026-05-01", end: "2026-05-31" },
                    createdAt: "2026-06-25T12:00:00.000Z",
                    scope: "customer",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/experimental/views/")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.listCustomViews();
        expect(response).toEqual({
            views: [
                {
                    displayId: "displayId",
                    name: "name",
                    description: "description",
                    status: "DRAFT",
                    queryCount: 1,
                    period: {
                        kind: "relative",
                        start: "2026-05-01",
                        end: "2026-05-31",
                    },
                    createdAt: "2026-06-25T12:00:00.000Z",
                    scope: "customer",
                },
            ],
        });
    });

    test("listCustomViews (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.listCustomViews();
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("listCustomViews (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.listCustomViews();
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("createCustomView (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Usage over time",
            queries: [
                {
                    id: "usage",
                    sql: "SELECT toDate(created_at) AS day, count() AS signals FROM fact_signal GROUP BY day ORDER BY day",
                },
            ],
            renderBundle: "<!doctype html><body>…</body>",
        };
        const rawResponseBody = {
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        };
        server
            .mockEndpoint()
            .post("/experimental/views/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.createCustomView({
            name: "Usage over time",
            queries: [
                {
                    id: "usage",
                    sql: "SELECT toDate(created_at) AS day, count() AS signals FROM fact_signal GROUP BY day ORDER BY day",
                },
            ],
            renderBundle: "<!doctype html><body>\u2026</body>",
        });
        expect(response).toEqual({
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        });
    });

    test("createCustomView (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            queries: [
                { id: "x", sql: "x" },
                { id: "x", sql: "x" },
            ],
            renderBundle: "x",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/experimental/views/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.createCustomView({
                name: "x",
                queries: [
                    {
                        id: "x",
                        sql: "x",
                    },
                    {
                        id: "x",
                        sql: "x",
                    },
                ],
                renderBundle: "x",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("createCustomView (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            queries: [
                { id: "x", sql: "x" },
                { id: "x", sql: "x" },
            ],
            renderBundle: "x",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/experimental/views/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.createCustomView({
                name: "x",
                queries: [
                    {
                        id: "x",
                        sql: "x",
                    },
                    {
                        id: "x",
                        sql: "x",
                    },
                ],
                renderBundle: "x",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("createCustomView (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            queries: [
                { id: "x", sql: "x" },
                { id: "x", sql: "x" },
            ],
            renderBundle: "x",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/experimental/views/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.createCustomView({
                name: "x",
                queries: [
                    {
                        id: "x",
                        sql: "x",
                    },
                    {
                        id: "x",
                        sql: "x",
                    },
                ],
                renderBundle: "x",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("publishCustomView (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        };
        server
            .mockEndpoint()
            .post("/experimental/views/displayId/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.publishCustomView({
            displayId: "displayId",
        });
        expect(response).toEqual({
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        });
    });

    test("publishCustomView (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/experimental/views/displayId/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.publishCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("publishCustomView (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/experimental/views/displayId/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.publishCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("publishCustomView (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/experimental/views/displayId/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.publishCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("updateCustomViewPeriod (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { period: { kind: "relative" } };
        const rawResponseBody = {
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId/period")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.updateCustomViewPeriod({
            displayId: "displayId",
            period: {
                kind: "relative",
            },
        });
        expect(response).toEqual({
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        });
    });

    test("updateCustomViewPeriod (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { period: { kind: "relative" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId/period")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomViewPeriod({
                displayId: "displayId",
                period: {
                    kind: "relative",
                },
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("updateCustomViewPeriod (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { period: { kind: "relative" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId/period")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomViewPeriod({
                displayId: "displayId",
                period: {
                    kind: "relative",
                },
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("updateCustomViewPeriod (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { period: { kind: "relative" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId/period")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomViewPeriod({
                displayId: "displayId",
                period: {
                    kind: "relative",
                },
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("updateCustomViewPeriod (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { period: { kind: "relative" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId/period")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomViewPeriod({
                displayId: "displayId",
                period: {
                    kind: "relative",
                },
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getCustomView (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            displayId: "displayId",
            name: "name",
            description: "description",
            status: "DRAFT",
            queryIds: ["queryIds"],
            renderBundle: "renderBundle",
            period: { kind: "relative", unit: "day", amount: 1, start: "2026-05-01", end: "2026-05-31" },
            filters: [{ name: "region", values: ["us", "eu", "apac"] }],
            scope: "customer",
        };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.getCustomView({
            displayId: "displayId",
        });
        expect(response).toEqual({
            displayId: "displayId",
            name: "name",
            description: "description",
            status: "DRAFT",
            queryIds: ["queryIds"],
            renderBundle: "renderBundle",
            period: {
                kind: "relative",
                unit: "day",
                amount: 1,
                start: "2026-05-01",
                end: "2026-05-31",
            },
            filters: [
                {
                    name: "region",
                    values: ["us", "eu", "apac"],
                },
            ],
            scope: "customer",
        });
    });

    test("getCustomView (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("getCustomView (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getCustomView (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("updateCustomView (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.updateCustomView({
            displayId: "displayId",
        });
        expect(response).toEqual({
            displayId: "view_3kf9a2",
            name: "name",
            status: "DRAFT",
            previewUrl: "https://app.paid.ai/custom-views/view_3kf9a2/preview",
            scope: "customer",
        });
    });

    test("updateCustomView (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("updateCustomView (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("updateCustomView (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("updateCustomView (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/experimental/views/displayId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.updateCustomView({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getCustomViewData (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { key: [{ key: "value" }] } };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.getCustomViewData({
            displayId: "displayId",
        });
        expect(response).toEqual({
            data: {
                key: [
                    {
                        key: "value",
                    },
                ],
            },
        });
    });

    test("getCustomViewData (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewData({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("getCustomViewData (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewData({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("getCustomViewData (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewData({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getCustomViewData (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(408)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewData({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.RequestTimeoutError);
    });

    test("getCustomViewData (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewData({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.TooManyRequestsError);
    });

    test("getCustomViewData (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/data")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewData({
                displayId: "displayId",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getCustomViewEmbedToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { token: "token", expiresAt: "2024-01-15T09:30:00Z" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/embed-token")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customViewsExperimental.getCustomViewEmbedToken({
            displayId: "displayId",
            customerId: "customerId",
        });
        expect(response).toEqual({
            token: "token",
            expiresAt: "2024-01-15T09:30:00Z",
        });
    });

    test("getCustomViewEmbedToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/embed-token")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewEmbedToken({
                displayId: "displayId",
                customerId: "x",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("getCustomViewEmbedToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/embed-token")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewEmbedToken({
                displayId: "displayId",
                customerId: "x",
            });
        }).rejects.toThrow(Paid.ForbiddenError);
    });

    test("getCustomViewEmbedToken (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/embed-token")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewEmbedToken({
                displayId: "displayId",
                customerId: "x",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getCustomViewEmbedToken (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/experimental/views/displayId/embed-token")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customViewsExperimental.getCustomViewEmbedToken({
                displayId: "displayId",
                customerId: "x",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });
});
