// This file was auto-generated by Fern from our API Definition.

import { PaidClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Products", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                externalId: "externalId",
                displayId: "displayId",
                organizationId: "organizationId",
                name: "name",
                description: "description",
                type: "agent",
                active: true,
                productCode: "productCode",
                ProductAttribute: [
                    {
                        name: "name",
                        active: true,
                        pricing: {
                            taxable: true,
                            chargeType: "oneTime",
                            pricingModel: "PerUnit",
                            billingFrequency: "monthly",
                            pricePoints: { key: {} },
                        },
                    },
                ],
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        ];
        server.mockEndpoint().get("/products").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.products.list();
        expect(response).toEqual([
            {
                id: "id",
                externalId: "externalId",
                displayId: "displayId",
                organizationId: "organizationId",
                name: "name",
                description: "description",
                type: "agent",
                active: true,
                productCode: "productCode",
                ProductAttribute: [
                    {
                        name: "name",
                        active: true,
                        pricing: {
                            taxable: true,
                            chargeType: "oneTime",
                            pricingModel: "PerUnit",
                            billingFrequency: "monthly",
                            pricePoints: {
                                key: {},
                            },
                        },
                    },
                ],
                metadata: {
                    key: "value",
                },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        ]);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Acme Product",
            description: "Acme Product does amazing things.",
            externalId: "acme-product",
            type: "product",
        };
        const rawResponseBody = {
            id: "63fd642c-569d-44f9-8d67-5cf4944a16cc",
            externalId: "acme-product",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "Acme Product",
            description: "Acme Product does amazing things.",
            type: "product",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: { key: {} },
                    },
                },
            ],
            metadata: { key: "value" },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.create({
            name: "Acme Product",
            description: "Acme Product does amazing things.",
            externalId: "acme-product",
            type: "product",
        });
        expect(response).toEqual({
            id: "63fd642c-569d-44f9-8d67-5cf4944a16cc",
            externalId: "acme-product",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "Acme Product",
            description: "Acme Product does amazing things.",
            type: "product",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: {
                            key: {},
                        },
                    },
                },
            ],
            metadata: {
                key: "value",
            },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: { key: {} },
                    },
                },
            ],
            metadata: { key: "value" },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/products/productId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.get("productId");
        expect(response).toEqual({
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: {
                            key: {},
                        },
                    },
                },
            ],
            metadata: {
                key: "value",
            },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: { key: {} },
                    },
                },
            ],
            metadata: { key: "value" },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .put("/products/productId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.update("productId", {});
        expect(response).toEqual({
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: {
                            key: {},
                        },
                    },
                },
            ],
            metadata: {
                key: "value",
            },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/products/productId").respondWith().statusCode(200).build();

        const response = await client.products.delete("productId");
        expect(response).toEqual(undefined);
    });

    test("getByExternalId", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: { key: {} },
                    },
                },
            ],
            metadata: { key: "value" },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/products/external/externalId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.getByExternalId("externalId");
        expect(response).toEqual({
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: {
                            key: {},
                        },
                    },
                },
            ],
            metadata: {
                key: "value",
            },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("updateByExternalId", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: { key: {} },
                    },
                },
            ],
            metadata: { key: "value" },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .put("/products/external/externalId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.updateByExternalId("externalId", {});
        expect(response).toEqual({
            id: "id",
            externalId: "externalId",
            displayId: "displayId",
            organizationId: "organizationId",
            name: "name",
            description: "description",
            type: "agent",
            active: true,
            productCode: "productCode",
            ProductAttribute: [
                {
                    name: "name",
                    active: true,
                    pricing: {
                        taxable: true,
                        chargeType: "oneTime",
                        pricingModel: "PerUnit",
                        billingFrequency: "monthly",
                        pricePoints: {
                            key: {},
                        },
                    },
                },
            ],
            metadata: {
                key: "value",
            },
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("deleteByExternalId", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/products/external/externalId").respondWith().statusCode(200).build();

        const response = await client.products.deleteByExternalId("externalId");
        expect(response).toEqual(undefined);
    });
});
