// This file was auto-generated by Fern from our API Definition.

import * as Paid from "../../src/api/index";
import { PaidClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Traces", () => {
    test("getTraces (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            traces: [
                {
                    name: "trace.openai.agents.on_agent",
                    vendor: "openai",
                    model: "gpt-4o-mini",
                    cost: { amount: 0.00001725, currency: "USD" },
                    startTimeUnixNano: "1759774597906209000",
                    endTimeUnixNano: "1759774599194165000",
                    attributes: {
                        gen_ai: {
                            system: "openai",
                            operation: { name: "on_agent" },
                            request: { model: "gpt-4o-mini" },
                            usage: { input_tokens: 27, output_tokens: 22 },
                        },
                        external_customer_id: "your_external_customer_id",
                        external_agent_id: "your_external_agent_id",
                    },
                    customerId: "customer_123",
                    productId: "product_456",
                },
                {
                    name: "trace.openai.agents.on_agent",
                    vendor: "openai",
                    model: "gpt-4o-mini",
                    cost: { amount: 0.0000219, currency: "USD" },
                    startTimeUnixNano: "1759774599472853000",
                    endTimeUnixNano: "1759774600619994000",
                    attributes: { gen_ai: { system: "openai", request: { model: "gpt-4o-mini" } } },
                    customerId: "customer_123",
                    productId: "product_456",
                },
            ],
            meta: {
                limit: 100,
                offset: 0,
                count: 2,
                hasMore: false,
                startTime: "2024-01-15T09:30:00Z",
                endTime: "2024-01-15T09:30:00Z",
                externalCustomerId: "externalCustomerId",
                externalProductId: "externalProductId",
                metadata: "metadata",
            },
        };
        server.mockEndpoint().get("/traces").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.traces.getTraces({
            limit: 1,
            offset: 1,
            startTime: "2024-01-15T09:30:00Z",
            endTime: "2024-01-15T09:30:00Z",
            externalCustomerId: "externalCustomerId",
            externalProductId: "externalProductId",
            externalAgentId: "externalAgentId",
            metadata: "metadata",
        });
        expect(response).toEqual({
            traces: [
                {
                    name: "trace.openai.agents.on_agent",
                    vendor: "openai",
                    model: "gpt-4o-mini",
                    cost: {
                        amount: 0.00001725,
                        currency: "USD",
                    },
                    startTimeUnixNano: "1759774597906209000",
                    endTimeUnixNano: "1759774599194165000",
                    attributes: {
                        gen_ai: {
                            system: "openai",
                            operation: {
                                name: "on_agent",
                            },
                            request: {
                                model: "gpt-4o-mini",
                            },
                            usage: {
                                input_tokens: 27,
                                output_tokens: 22,
                            },
                        },
                        external_customer_id: "your_external_customer_id",
                        external_agent_id: "your_external_agent_id",
                    },
                    customerId: "customer_123",
                    productId: "product_456",
                },
                {
                    name: "trace.openai.agents.on_agent",
                    vendor: "openai",
                    model: "gpt-4o-mini",
                    cost: {
                        amount: 0.0000219,
                        currency: "USD",
                    },
                    startTimeUnixNano: "1759774599472853000",
                    endTimeUnixNano: "1759774600619994000",
                    attributes: {
                        gen_ai: {
                            system: "openai",
                            request: {
                                model: "gpt-4o-mini",
                            },
                        },
                    },
                    customerId: "customer_123",
                    productId: "product_456",
                },
            ],
            meta: {
                limit: 100,
                offset: 0,
                count: 2,
                hasMore: false,
                startTime: "2024-01-15T09:30:00Z",
                endTime: "2024-01-15T09:30:00Z",
                externalCustomerId: "externalCustomerId",
                externalProductId: "externalProductId",
                metadata: "metadata",
            },
        });
    });

    test("getTraces (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: {} };
        server.mockEndpoint().get("/traces").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.traces.getTraces();
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("getTraces (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: {} };
        server.mockEndpoint().get("/traces").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.traces.getTraces();
        }).rejects.toThrow(Paid.ForbiddenError);
    });
});
