// This file was auto-generated by Fern from our API Definition.

import * as Paid from "../../src/api/index";
import { PaidClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ValueReceipts", () => {
    test("listValueReceipts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    status: "status",
                    publicUrlToken: "publicUrlToken",
                    publicUrl: "publicUrl",
                    isPublished: true,
                    customerId: "customerId",
                    customerName: "customerName",
                    customerExternalId: "customerExternalId",
                    orderId: "orderId",
                    currency: "currency",
                    startDate: "2024-01-15T09:30:00Z",
                    endDate: "2024-01-15T09:30:00Z",
                    totalDeliveredValue: 1.1,
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
            total: 1,
        };
        server.mockEndpoint().get("/value-receipts/").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.valueReceipts.listValueReceipts();
        expect(response).toEqual({
            data: [
                {
                    id: "id",
                    status: "status",
                    publicUrlToken: "publicUrlToken",
                    publicUrl: "publicUrl",
                    isPublished: true,
                    customerId: "customerId",
                    customerName: "customerName",
                    customerExternalId: "customerExternalId",
                    orderId: "orderId",
                    currency: "currency",
                    startDate: "2024-01-15T09:30:00Z",
                    endDate: "2024-01-15T09:30:00Z",
                    totalDeliveredValue: 1.1,
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
            total: 1,
        });
    });

    test("listValueReceipts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/value-receipts/").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.valueReceipts.listValueReceipts();
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getValueReceiptById (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            status: "status",
            publicUrlToken: "publicUrlToken",
            publicUrl: "publicUrl",
            isPublished: true,
            customerId: "customerId",
            customerName: "customerName",
            customerExternalId: "customerExternalId",
            orderId: "orderId",
            currency: "currency",
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
            totalDeliveredValue: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            publishedAt: "2024-01-15T09:30:00Z",
            publishExpiresAt: "2024-01-15T09:30:00Z",
            allowEmbed: true,
        };
        server.mockEndpoint().get("/value-receipts/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.valueReceipts.getValueReceiptById({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            status: "status",
            publicUrlToken: "publicUrlToken",
            publicUrl: "publicUrl",
            isPublished: true,
            customerId: "customerId",
            customerName: "customerName",
            customerExternalId: "customerExternalId",
            orderId: "orderId",
            currency: "currency",
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
            totalDeliveredValue: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            publishedAt: "2024-01-15T09:30:00Z",
            publishExpiresAt: "2024-01-15T09:30:00Z",
            allowEmbed: true,
        });
    });

    test("getValueReceiptById (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/value-receipts/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.valueReceipts.getValueReceiptById({
                id: "id",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getValueReceiptById (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/value-receipts/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.valueReceipts.getValueReceiptById({
                id: "id",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("publishValueReceipt (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            status: "status",
            publicUrlToken: "publicUrlToken",
            publicUrl: "publicUrl",
            isPublished: true,
            customerId: "customerId",
            customerName: "customerName",
            customerExternalId: "customerExternalId",
            orderId: "orderId",
            currency: "currency",
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
            totalDeliveredValue: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            publishedAt: "2024-01-15T09:30:00Z",
            publishExpiresAt: "2024-01-15T09:30:00Z",
            allowEmbed: true,
        };
        server
            .mockEndpoint()
            .post("/value-receipts/id/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.valueReceipts.publishValueReceipt({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            status: "status",
            publicUrlToken: "publicUrlToken",
            publicUrl: "publicUrl",
            isPublished: true,
            customerId: "customerId",
            customerName: "customerName",
            customerExternalId: "customerExternalId",
            orderId: "orderId",
            currency: "currency",
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
            totalDeliveredValue: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            publishedAt: "2024-01-15T09:30:00Z",
            publishExpiresAt: "2024-01-15T09:30:00Z",
            allowEmbed: true,
        });
    });

    test("publishValueReceipt (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/value-receipts/id/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueReceipts.publishValueReceipt({
                id: "id",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("publishValueReceipt (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/value-receipts/id/publish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueReceipts.publishValueReceipt({
                id: "id",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("unpublishValueReceipt (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            status: "status",
            publicUrlToken: "publicUrlToken",
            publicUrl: "publicUrl",
            isPublished: true,
            customerId: "customerId",
            customerName: "customerName",
            customerExternalId: "customerExternalId",
            orderId: "orderId",
            currency: "currency",
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
            totalDeliveredValue: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            publishedAt: "2024-01-15T09:30:00Z",
            publishExpiresAt: "2024-01-15T09:30:00Z",
            allowEmbed: true,
        };
        server
            .mockEndpoint()
            .post("/value-receipts/id/unpublish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.valueReceipts.unpublishValueReceipt({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            status: "status",
            publicUrlToken: "publicUrlToken",
            publicUrl: "publicUrl",
            isPublished: true,
            customerId: "customerId",
            customerName: "customerName",
            customerExternalId: "customerExternalId",
            orderId: "orderId",
            currency: "currency",
            startDate: "2024-01-15T09:30:00Z",
            endDate: "2024-01-15T09:30:00Z",
            totalDeliveredValue: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            publishedAt: "2024-01-15T09:30:00Z",
            publishExpiresAt: "2024-01-15T09:30:00Z",
            allowEmbed: true,
        });
    });

    test("unpublishValueReceipt (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/value-receipts/id/unpublish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueReceipts.unpublishValueReceipt({
                id: "id",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("unpublishValueReceipt (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/value-receipts/id/unpublish")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueReceipts.unpublishValueReceipt({
                id: "id",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });
});
