// This file was auto-generated by Fern from our API Definition.

import * as Paid from "../../src/api/index";
import { PaidClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ValueMetrics", () => {
    test("listValueMetrics (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    slug: "slug",
                    name: "name",
                    category: "category",
                    unit: { type: "monetary", unit: "tickets", unitDisplay: "tickets resolved" },
                    description: "description",
                    archivedAt: "archivedAt",
                    monetaryConversion: {
                        valuePerUnit: null,
                        label: null,
                        expression: "expression",
                        variables: [{ id: "id", label: "label", default: 1.1 }],
                    },
                },
            ],
            pagination: { limit: 1, offset: 1, total: 1, hasMore: true },
        };
        server.mockEndpoint().get("/value-metrics/").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.valueMetrics.listValueMetrics();
        expect(response).toEqual({
            data: [
                {
                    slug: "slug",
                    name: "name",
                    category: "category",
                    unit: {
                        type: "monetary",
                        unit: "tickets",
                        unitDisplay: "tickets resolved",
                    },
                    description: "description",
                    archivedAt: "archivedAt",
                    monetaryConversion: {
                        valuePerUnit: null,
                        label: null,
                        expression: "expression",
                        variables: [
                            {
                                id: "id",
                                label: "label",
                                default: 1.1,
                            },
                        ],
                    },
                },
            ],
            pagination: {
                limit: 1,
                offset: 1,
                total: 1,
                hasMore: true,
            },
        });
    });

    test("listValueMetrics (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/value-metrics/").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.valueMetrics.listValueMetrics();
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("listValueMetrics (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/value-metrics/").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.valueMetrics.listValueMetrics();
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("createValueMetric (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Time saved",
            unit: { type: "monetary" },
            formula: { expression: "minutes_saved / 60", variables: [{ id: "id", label: "label" }] },
            signal: { eventName: "ticket_resolved" },
        };
        const rawResponseBody = { slug: "slug", name: "name", version: 1 };
        server
            .mockEndpoint()
            .post("/value-metrics/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.valueMetrics.createValueMetric({
            name: "Time saved",
            unit: {
                type: "monetary",
            },
            formula: {
                expression: "minutes_saved / 60",
                variables: [
                    {
                        id: "id",
                        label: "label",
                    },
                ],
            },
            signal: {
                eventName: "ticket_resolved",
            },
        });
        expect(response).toEqual({
            slug: "slug",
            name: "name",
            version: 1,
        });
    });

    test("createValueMetric (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            unit: { type: "monetary" },
            formula: {
                expression: "x",
                variables: [
                    { id: "x", label: "x" },
                    { id: "x", label: "x" },
                ],
            },
            signal: { eventName: "x" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/value-metrics/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.createValueMetric({
                name: "x",
                unit: {
                    type: "monetary",
                },
                formula: {
                    expression: "x",
                    variables: [
                        {
                            id: "x",
                            label: "x",
                        },
                        {
                            id: "x",
                            label: "x",
                        },
                    ],
                },
                signal: {
                    eventName: "x",
                },
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("createValueMetric (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            unit: { type: "monetary" },
            formula: {
                expression: "x",
                variables: [
                    { id: "x", label: "x" },
                    { id: "x", label: "x" },
                ],
            },
            signal: { eventName: "x" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/value-metrics/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.createValueMetric({
                name: "x",
                unit: {
                    type: "monetary",
                },
                formula: {
                    expression: "x",
                    variables: [
                        {
                            id: "x",
                            label: "x",
                        },
                        {
                            id: "x",
                            label: "x",
                        },
                    ],
                },
                signal: {
                    eventName: "x",
                },
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("createValueMetric (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            unit: { type: "monetary" },
            formula: {
                expression: "x",
                variables: [
                    { id: "x", label: "x" },
                    { id: "x", label: "x" },
                ],
            },
            signal: { eventName: "x" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/value-metrics/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.createValueMetric({
                name: "x",
                unit: {
                    type: "monetary",
                },
                formula: {
                    expression: "x",
                    variables: [
                        {
                            id: "x",
                            label: "x",
                        },
                        {
                            id: "x",
                            label: "x",
                        },
                    ],
                },
                signal: {
                    eventName: "x",
                },
            });
        }).rejects.toThrow(Paid.ConflictError);
    });

    test("createValueMetric (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "x",
            unit: { type: "monetary" },
            formula: {
                expression: "x",
                variables: [
                    { id: "x", label: "x" },
                    { id: "x", label: "x" },
                ],
            },
            signal: { eventName: "x" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/value-metrics/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.createValueMetric({
                name: "x",
                unit: {
                    type: "monetary",
                },
                formula: {
                    expression: "x",
                    variables: [
                        {
                            id: "x",
                            label: "x",
                        },
                        {
                            id: "x",
                            label: "x",
                        },
                    ],
                },
                signal: {
                    eventName: "x",
                },
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("getValueMetric (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            slug: "slug",
            name: "name",
            category: "category",
            unit: { type: "monetary", durationUnit: "seconds", unit: "tickets", unitDisplay: "tickets resolved" },
            description: "description",
            longDescription: "longDescription",
            sources: [{ name: "name", url: "url" }],
            archivedAt: "archivedAt",
            monetaryConversion: {
                valuePerUnit: 1.1,
                label: "label",
                expression: "expression",
                variables: [{ id: "id", label: "label", default: 1.1 }],
            },
            formula: { id: "id", label: "label", expression: "expression", variables: [{ id: "id", label: "label" }] },
            signals: [
                {
                    eventName: "ticket_resolved",
                    label: "label",
                    defaults: { key: 1.1 },
                    description: "description",
                    labels: ["labels"],
                    tags: ["tags"],
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/value-metrics/slug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.valueMetrics.getValueMetric({
            slug: "slug",
        });
        expect(response).toEqual({
            slug: "slug",
            name: "name",
            category: "category",
            unit: {
                type: "monetary",
                durationUnit: "seconds",
                unit: "tickets",
                unitDisplay: "tickets resolved",
            },
            description: "description",
            longDescription: "longDescription",
            sources: [
                {
                    name: "name",
                    url: "url",
                },
            ],
            archivedAt: "archivedAt",
            monetaryConversion: {
                valuePerUnit: 1.1,
                label: "label",
                expression: "expression",
                variables: [
                    {
                        id: "id",
                        label: "label",
                        default: 1.1,
                    },
                ],
            },
            formula: {
                id: "id",
                label: "label",
                expression: "expression",
                variables: [
                    {
                        id: "id",
                        label: "label",
                    },
                ],
            },
            signals: [
                {
                    eventName: "ticket_resolved",
                    label: "label",
                    defaults: {
                        key: 1.1,
                    },
                    description: "description",
                    labels: ["labels"],
                    tags: ["tags"],
                },
            ],
        });
    });

    test("getValueMetric (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/value-metrics/slug")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.getValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("getValueMetric (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/value-metrics/slug")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.getValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("archiveValueMetric (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { slug: "slug", name: "name", version: 1 };
        server
            .mockEndpoint()
            .delete("/value-metrics/slug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.valueMetrics.archiveValueMetric({
            slug: "slug",
        });
        expect(response).toEqual({
            slug: "slug",
            name: "name",
            version: 1,
        });
    });

    test("archiveValueMetric (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/value-metrics/slug")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.archiveValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("archiveValueMetric (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/value-metrics/slug")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.archiveValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("archiveValueMetric (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/value-metrics/slug")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.archiveValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.ConflictError);
    });

    test("archiveValueMetric (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/value-metrics/slug")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.archiveValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });

    test("updateValueMetric (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { slug: "slug", name: "name", version: 1 };
        server
            .mockEndpoint()
            .patch("/value-metrics/slug")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.valueMetrics.updateValueMetric({
            slug: "slug",
        });
        expect(response).toEqual({
            slug: "slug",
            name: "name",
            version: 1,
        });
    });

    test("updateValueMetric (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/value-metrics/slug")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.updateValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.BadRequestError);
    });

    test("updateValueMetric (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/value-metrics/slug")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.updateValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.NotFoundError);
    });

    test("updateValueMetric (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/value-metrics/slug")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.updateValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.ConflictError);
    });

    test("updateValueMetric (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PaidClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/value-metrics/slug")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.valueMetrics.updateValueMetric({
                slug: "slug",
            });
        }).rejects.toThrow(Paid.InternalServerError);
    });
});
