// This file was auto-generated by Fern from our API Definition.

import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { ContactsClient } from "./api/resources/contacts/client/Client.js";
import { CustomersClient } from "./api/resources/customers/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { PlansClient } from "./api/resources/plans/client/Client.js";
import { ProductsClient } from "./api/resources/products/client/Client.js";
import { TracesClient } from "./api/resources/traces/client/Client.js";
import { UsageClient } from "./api/resources/usage/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";

export declare namespace PaidClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PaidClient {
    protected readonly _options: NormalizedClientOptions<PaidClient.Options>;
    protected _customers: CustomersClient | undefined;
    protected _agents: AgentsClient | undefined;
    protected _products: ProductsClient | undefined;
    protected _contacts: ContactsClient | undefined;
    protected _orders: OrdersClient | undefined;
    protected _plans: PlansClient | undefined;
    protected _usage: UsageClient | undefined;
    protected _traces: TracesClient | undefined;

    constructor(options: PaidClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get customers(): CustomersClient {
        return (this._customers ??= new CustomersClient(this._options));
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }

    public get products(): ProductsClient {
        return (this._products ??= new ProductsClient(this._options));
    }

    public get contacts(): ContactsClient {
        return (this._contacts ??= new ContactsClient(this._options));
    }

    public get orders(): OrdersClient {
        return (this._orders ??= new OrdersClient(this._options));
    }

    public get plans(): PlansClient {
        return (this._plans ??= new PlansClient(this._options));
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }

    public get traces(): TracesClient {
        return (this._traces ??= new TracesClient(this._options));
    }
}
